### ISSUE TITLE
Missing diags.yml causes exception 

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch-support-diagnostics#101]
If diags.yml is missing then the following exception is thrown. We should see if the file exists and if not throw a better error for the user to understand the problem. 

```
loki:support-diagnostics-2.0.6 jeremy$ ./diagnostics.sh  --host atuin
Using /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Execution Error
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200) ~[snakeyaml-1.15.jar:na]
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60) ~[snakeyaml-1.15.jar:na]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:381) ~[snakeyaml-1.15.jar:na]
	at com.elastic.support.util.JsonYamlUtils.readYaml(JsonYamlUtils.java:96) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.util.JsonYamlUtils.readYamlFromClasspath(JsonYamlUtils.java:73) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:13) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) ~[support-diagnostics-2.0.6.jar:2.0.6]
Caused by: java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74) ~[na:1.8.0_60]
	at java.io.PushbackInputStream.read(PushbackInputStream.java:166) ~[na:1.8.0_60]
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:90) ~[snakeyaml-1.15.jar:na]
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:122) ~[snakeyaml-1.15.jar:na]
	at java.io.Reader.read(Reader.java:140) ~[na:1.8.0_60]
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184) ~[snakeyaml-1.15.jar:na]
	... 6 common frames omitted
```

**Comment by astefan** [comment]
The `InputStream` returned here can be null if it doesn't exist, according to the Java API: https://github.com/elastic/elasticsearch-support-diagnostics/blob/master/src/main/java/com/elastic/support/util/JsonYamlUtils.java#L71 Maybe check if it's null before passing it to the snakeyaml library and throw a more descriptive exception?

**Comment by nemonster** [comment]
i guess.  But I read  a lot of files here.  The  question would be, given that the diags,yml comes along in the distribution, why it would be missing?  I

**Comment by nemonster** [comment]
Fixed in current release.
