### ISSUE TITLE
java.io.FileNotFoundException for password scrub

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch-support-diagnostics#102]
I had elasticsearch started with `-Des.path.conf=` set, which did not collect. Threw the error below without completing.
```
Diagnostic query: watcher was retrieved and saved to disk.
Retrieving network interface information.
Processing logs and configuration files.
Processed logs and configs for node: The Night Man
Finished processing logs and configuration files.
Scrubbing elasticsearch config.
Error redacting config passwords.
java.io.FileNotFoundException: /Users/jared/Downloads/support-diagnostics-2.0.6/diagnostics/The Night Man-log and config/config/elasticsearch.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_65]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_65]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_65]
	at com.elastic.support.util.JsonYamlUtils.readYamlFromPath(JsonYamlUtils.java:81) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.commands.ScrubPasswordsCmd.redactConfig(ScrubPasswordsCmd.java:54) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.commands.ScrubPasswordsCmd.execute(ScrubPasswordsCmd.java:34) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.chain.Chain.execute(Chain.java:33) [support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:19) [support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) [support-diagnostics-2.0.6.jar:2.0.6]
Execution Error
java.lang.RuntimeException: java.io.FileNotFoundException: /Users/jared/Downloads/support-diagnostics-2.0.6/diagnostics/The Night Man-log and config/config/elasticsearch.yml (No such file or directory)
	at com.elastic.support.diagnostics.commands.ScrubPasswordsCmd.execute(ScrubPasswordsCmd.java:44) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:19) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) ~[support-diagnostics-2.0.6.jar:2.0.6]
Caused by: java.io.FileNotFoundException: /Users/jared/Downloads/support-diagnostics-2.0.6/diagnostics/The Night Man-log and config/config/elasticsearch.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_65]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_65]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_65]
	at com.elastic.support.util.JsonYamlUtils.readYamlFromPath(JsonYamlUtils.java:81) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.commands.ScrubPasswordsCmd.redactConfig(ScrubPasswordsCmd.java:54) ~[support-diagnostics-2.0.6.jar:2.0.6]
	at com.elastic.support.diagnostics.commands.ScrubPasswordsCmd.execute(ScrubPasswordsCmd.java:34) ~[support-diagnostics-2.0.6.jar:2.0.6]
	... 4 common frames omitted
```

**Comment by pickypg** [comment]
What happens if you remove the whitespace from the directory name?

**Comment by jpcarey** [comment]
@pickypg the file was never collected.

```
$ file '/Users/jared/Downloads/support-diagnostics-2.0.6/diagnostics/The Night Man-log and config/config/elasticsearch.yml'
/Users/jared/Downloads/support-diagnostics-2.0.6/diagnostics/The Night Man-log and config/config/elasticsearch.yml: cannot open `/Users/jared/Downloads/support-diagnostics-2.0.6/diagnostics/The Night Man-log and config/config/elasticsearch.yml' (No such file or directory)
```

**Comment by nemonster** [comment]
I can duplicate this if there are no entries in the elasticsearch.yml file.  That's the default setup for ES out of the box, but at least in 2.x environments network.host needs to be explicitly set at the very least.  And it's kind of an issue if things like bootstrap.mlockall and the minimum master settings aren't there.

So short term, adding at least one property to elasticsearch.yml ought to get it past this.  Longer term I'll make sure it keeps going even if there isn't any content and flag as a source of concern.

**Comment by nemonster** [comment]
Fixed in current release.
