### ISSUE TITLE
Detect existence of `ss` application

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#106]
If the `ss` application is not installed, this error occurs:

```
Error processing system commands 
java.io.IOException: Cannot run program "ss": error=2, No such file or directory 
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041) ~[na:1.7.0_25] 
at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:41) ~[support-diagnostics-2.0.7.jar:2.0.7] 
at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-2.0.7.jar:2.0.7] 
at com.elastic.support.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-2.0.7.jar:2.0.7] 
at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:35) ~[support-diagnostics-2.0.7.jar:2.0.7] 
at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) ~[support-diagnostics-2.0.7.jar:2.0.7] 
Caused by: java.io.IOException: error=2, No such file or directory 
at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.7.0_25] 
at java.lang.UNIXProcess.<init>(UNIXProcess.java:135) ~[na:1.7.0_25] 
at java.lang.ProcessImpl.start(ProcessImpl.java:130) ~[na:1.7.0_25] 
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022) ~[na:1.7.0_25] 
... 5 common frames omitted
```

**Comment by nemonster** [comment]
Cannot reliably detect the presence of these kinds of things.  Just not feasible.  Have fixed the issue however that would cause the rest of the system calls to fail.  It will just log the error that it didn't find and go ahead with the rest of them.

**Comment by robin13** [comment]
Would it be possible to test if the application (first element of each [of these](https://github.com/elastic/elasticsearch-support-diagnostics/blob/342885edd4c89eeb4d7cdc34e706b582cc7306be/src/main/resources/diags.yml#L107)) exists and is executable before executing it?  Typical procedure for many bash scripts...

**Comment by nemonster** [comment]
It's not a bash script though. so it's an extra call for each command, and then trying to parse out each result.  Given that it's not going to cause the program to exit, I don't think that's necessarily worth that much effort unless there's some compelling reason to do so other than that you don't want to see the error.
