### ISSUE TITLE
Don't abort on failure to detect operating system

### ISSUE THREAD

**Issue by loekvangool** [elastic/elasticsearch-support-diagnostics#116]
```
Finished processing logs and configuration files.
Failed to detect operating system!
Error encountered running diagnostic. See logs for additional information.  Exiting application.
java.lang.RuntimeException: Unsupported OS
    at com.elastic.support.diagnostics.commands.SystemCallsCmd.checkOS(SystemCallsCmd.java:64) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:13) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:42) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:46) [support-diagnostics-2.0.9.jar:2.0.9]
Execution Error
java.lang.RuntimeException: Diagnostic runtime error
    at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:45) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:46) ~[support-diagnostics-2.0.9.jar:2.0.9]
Caused by: java.lang.RuntimeException: Unsupported OS
    at com.elastic.support.diagnostics.commands.SystemCallsCmd.checkOS(SystemCallsCmd.java:64) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:13) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-2.0.9.jar:2.0.9]
    at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:42) ~[support-diagnostics-2.0.9.jar:2.0.9]
    ... 1 common frames omitted
m-logstash-test01$ 
```

An unsupported OS should not lead to an abort, but rather to a red flag in the diagnostics tool.

Using 2.0.8

**Comment by nemonster** [comment]
Does this occur if you are running using the -remote option?  And what OS is this?  If it's unsupported/unknown you can't very well make a decision about what system calls to make.  Given that it *is* a diagnostic tool for support I'm curious what the rationale for making it work with an unsupported operating system would be?  Especially given the remote option.

**Comment by loekvangool** [comment]
Because of the sequence of the API calls, the diagnostic tool still exported (all?) files that we needed to run the Stats Analyzer, even while it was aborting later. Hence the abort looked a bit excessive. Would a warning suffice in this case?

**Comment by nemonster** [comment]
Actually no.  If you want to run it on an unsupported OS, run it using --type remote.  That way it will only execute the REST API.  It's a support tool.  And as such it's not intended for unsupported operating systems It's extra work to go through handling a situation it's not supposed to be used in when there's an alternative call available.  If the OS is unsupported I don't think it should be run in a mode where what it tries to collect is based on the assumption of a known quantity: OSX, Windows, or LInux.
