### ISSUE TITLE
elasticsearch-support-diagnostics - Issue

### ISSUE THREAD

**Issue by gigsvinoth** [elastic/elasticsearch-support-diagnostics#144]
2017-02-17 11:36:14,796 INFO  - Results will be written to: D:\ElasticSearch\support-diagnostics-5.0-dist_testupdated\support-diagnostics-5.0
2017-02-17 11:36:15,420 INFO  - Configuring REST endpoint.
2017-02-17 11:36:27,932 INFO  - Trying REST Endpoint.
2017-02-17 11:36:28,836 ERROR - Diagnostic query: nullfailed.
java.lang.IllegalArgumentException: Host may not be blank
	at org.apache.http.util.Args.notBlank(Args.java:74) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.cookie.CookieOrigin.<init>(CookieOrigin.java:51) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:141) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at com.elastic.support.util.RestModule.submitRequest(RestModule.java:58) [support-diagnostics-2.1.3.jar:2.1.3]
	at com.elastic.support.util.RestModule.submitRequest(RestModule.java:44) [support-diagnostics-2.1.3.jar:2.1.3]
	at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:26) [support-diagnostics-2.1.3.jar:2.1.3]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-2.1.3.jar:2.1.3]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-2.1.3.jar:2.1.3]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) [support-diagnostics-2.1.3.jar:2.1.3]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:54) [support-diagnostics-2.1.3.jar:2.1.3]
2017-02-17 11:36:32,175 ERROR - Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified

**Comment by joshuar** [comment]
Hi @gigsvinoth,

Could you provide some context here?  What version of the diagnostics?  What command-line options did you specify (excluding any sensitive information like passwords)?

**Comment by gigsvinoth** [comment]
Hi joshuar,
Thanks for reply
We are using 
Elastic Search version 1.5.1 
java version "1.8.0_112". 
diagnostic tool version - support-diagnostics-5.0

We are facing slowness in execution of functional Query in elastic search. so i have tried to diagnostic the issue. but we are getting above issue while executing the diagnostic tool
Thanks

**Comment by nemonster** [comment]
Hi gigsvinoth,
The key is in this line:
java.lang.IllegalArgumentException: Host may not be blank

You have to pass the --host <hostname> parameter at a minimum for it to work. I'd suggest going back to the readme for some examples. And I wouldn't bank on anything necessarily jumping out there on your query execution issue. As noted, this utility collects the server statistics via the available REST calls and packages them. So it's more of a convenience - you could run any of these individually. Feel free to check it out for what's available but it won't tell you anything in and of itself. You'll still have to analyze the results. If you're having difficulties in this area, I'd urge you to reach out to our sales organization and check into a support contract.
