### ISSUE TITLE
If executed without params, display help instead of a stacktrace.

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#154]
Currently when `./diagnostics.sh` is executed without params it results in an error with stacktrace.
I think it would be more convenient to display just the error (e.g. `Host may not be blank`) and the `-h` output instead.

```
% ./diagnostics.sh                                                                                                                         
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Results will be written to: /home/jakommo/Downloads/support-diagnostics-5.12
Creating /home/jakommo/Downloads/support-diagnostics-5.12/diagnostics as temporary directory.

Configuring REST endpoint.
Trying REST Endpoint.
Diagnostic query: nullfailed.
java.lang.IllegalArgumentException: Host may not be blank
	at org.apache.http.util.Args.notBlank(Args.java:74) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.cookie.CookieOrigin.<init>(CookieOrigin.java:51) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:141) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at com.elastic.support.util.RestModule.submitRequest(RestModule.java:58) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.util.RestModule.submitRequest(RestModule.java:44) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:26) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:54) [support-diagnostics-5.12.jar:5.12]
Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified
java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:822) ~[jackson-core-2.5.3.jar:2.5.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-databind-2.5.3.jar:2.5.3]
	at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:28) ~[support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) [support-diagnostics-5.12.jar:5.12]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:54) [support-diagnostics-5.12.jar:5.12]
Run 1 of 1 completed.

```

**Comment by nemonster** [comment]
This will be fixed in the next release. I used to have this set as a required field and it somehow got removed so the automatic check wasn't catching it.
