### ISSUE TITLE
NullPointerException when running diagnostics.sh script with --noVerify on localhost

### ISSUE THREAD

**Issue by Mogztter** [elastic/elasticsearch-support-diagnostics#169]
**Elasticsearch version**: 5.5.2

The following command is working fine:
```
./diagnostics.sh --host es.cluster.fr --noVerify --ssl -u username -p
```

But when running with `--noVerify` option on `localhost`, the following exception is thrown:
```
./diagnostics.sh --host localhost --noVerify --ssl -u username -p
```

```
Error encountered running diagnostic. See logs for additional information.  Exiting application.
java.lang.NullPointerException: null
        at java.lang.String.replace(String.java:2240) ~[na:1.8.0_112]
        at com.elastic.support.diagnostics.commands.BaseSystemCallsCmd.executeCalls(BaseSystemCallsCmd.java:26) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:17) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:55) [support-diagnostics-5.13.jar:5.13]
Execution Error
java.lang.RuntimeException: Diagnostic runtime error
        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:44) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:55) ~[support-diagnostics-5.13.jar:5.13]
Caused by: java.lang.NullPointerException: null
        at java.lang.String.replace(String.java:2240) ~[na:1.8.0_112]
        at com.elastic.support.diagnostics.commands.BaseSystemCallsCmd.executeCalls(BaseSystemCallsCmd.java:26) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.commands.SystemCallsCmd.execute(SystemCallsCmd.java:17) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-5.13.jar:5.13]
        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-5.13.jar:5.13]
        ... 1 common frames omitted
```

**Comment by nemonster** [comment]
Addressed in the 6.2 release.
