### ISSUE TITLE
NPE when running diagnostic tool

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch-support-diagnostics#174]
Output:

```
diagnostic crashing
===================
Configuring REST endpoint.
Trying REST Endpoint.
 was submitted
Currently running the following query:alias
Diagnostic query: alias was retrieved and saved to disk.
Currently running the following query:allocation
Diagnostic query: allocation was retrieved and saved to disk.
Currently running the following query:cat_master
Diagnostic query: cat_master was retrieved and saved to disk.
Currently running the following query:cat_nodes
Diagnostic query: cat_nodes was retrieved and saved to disk.
Currently running the following query:cat_indices
Diagnostic query: cat_indices was retrieved and saved to disk.
Currently running the following query:cat_segments
Diagnostic query: cat_segments was retrieved and saved to disk.
Currently running the following query:cat_health
Diagnostic query: cat_health was retrieved and saved to disk.
Currently running the following query:cat_pending_tasks
Diagnostic query: cat_pending_tasks was retrieved and saved to disk.
Currently running the following query:cat_aliases
cat_aliases query returned: 404/Not Found
Diagnostic query: cat_aliases was retrieved and saved to disk.
Currently running the following query:cat_thread_pool
Diagnostic query: cat_thread_pool was retrieved and saved to disk.
Currently running the following query:cat_fielddata
Diagnostic query: cat_fielddata was retrieved and saved to disk.
Currently running the following query:cat_shards
Diagnostic query: cat_shards was retrieved and saved to disk.
Currently running the following query:cluster_health
Diagnostic query: cluster_health was retrieved and saved to disk.
Currently running the following query:cluster_pending_tasks
Diagnostic query: cluster_pending_tasks was retrieved and saved to disk.
Currently running the following query:cluster_settings
Diagnostic query: cluster_settings was retrieved and saved to disk.
Currently running the following query:cluster_settings_defaults
Diagnostic query: cluster_settings_defaults was retrieved and saved to disk.
Currently running the following query:cluster_state
Diagnostic query: cluster_state was retrieved and saved to disk.
Currently running the following query:cluster_stats
Diagnostic query: cluster_stats was retrieved and saved to disk.
Currently running the following query:count
Diagnostic query: count was retrieved and saved to disk.
Currently running the following query:indices_stats
Diagnostic query: indices_stats was retrieved and saved to disk.
Currently running the following query:licenses
Diagnostic query: licenses was retrieved and saved to disk.
Currently running the following query:mapping
Diagnostic query: mapping was retrieved and saved to disk.
Currently running the following query:master
Diagnostic query: master was retrieved and saved to disk.
Currently running the following query:nodes_hot_threads
Diagnostic query: nodes_hot_threads was retrieved and saved to disk.
Currently running the following query:nodes_stats
Diagnostic query: nodes_stats was retrieved and saved to disk.
Currently running the following query:fielddata_stats
Diagnostic query: fielddata_stats was retrieved and saved to disk.
Currently running the following query:fielddata
Diagnostic query: fielddata was retrieved and saved to disk.
Currently running the following query:plugins
Diagnostic query: plugins was retrieved and saved to disk.
Currently running the following query:cat_recovery
Diagnostic query: cat_recovery was retrieved and saved to disk.
Currently running the following query:recovery
Diagnostic query: recovery was retrieved and saved to disk.
Currently running the following query:shards
Diagnostic query: shards was retrieved and saved to disk.
Currently running the following query:segments
Diagnostic query: segments was retrieved and saved to disk.
Currently running the following query:settings
Diagnostic query: settings was retrieved and saved to disk.
Currently running the following query:version
Diagnostic query: version was retrieved and saved to disk.
Currently running the following query:nodes
Diagnostic query: nodes was retrieved and saved to disk.
Currently running the following query:templates
Diagnostic query: templates was retrieved and saved to disk.
Currently running the following query:nodeattrs
Diagnostic query: nodeattrs was retrieved and saved to disk.
Currently running the following query:tasks
Diagnostic query: tasks was retrieved and saved to disk.
Currently running the following query:pipelines
Diagnostic query: pipelines was retrieved and saved to disk.
Currently running the following query:allocation_explain
Diagnostic query: allocation_explain was retrieved and saved to disk.
Currently running the following query:allocation_explain_disk
Diagnostic query: allocation_explain_disk was retrieved and saved to disk.
Currently running the following query:shard_stores
Diagnostic query: shard_stores was retrieved and saved to disk.
Currently running the following query:xpack
Diagnostic query: xpack was retrieved and saved to disk.
Currently running the following query:ml_datafeeds
Diagnostic query: ml_datafeeds was retrieved and saved to disk.
Currently running the following query:ml_anomaly_detectors
Diagnostic query: ml_anomaly_detectors was retrieved and saved to disk.
Currently running the following query:watcher_stats
Diagnostic query: watcher_stats was retrieved and saved to disk.
Currently running the following query:security_users
Diagnostic query: security_users was retrieved and saved to disk.
Currently running the following query:security_roles
Diagnostic query: security_roles was retrieved and saved to disk.
Currently running the following query:security_role_mappings
security_role_mappings query returned: 404/Not Found
Diagnostic query: security_role_mappings was retrieved and saved to disk.
Retrieving network interface information.
Attribute: diagNodecannot be converted since it is null
Processing logs and configuration files.
Error encountered running diagnostic. See logs for additional information.  Exiting application.
java.lang.NullPointerException: null
	at com.elastic.support.diagnostics.commands.LogAndConfigCmd.execute(LogAndConfigCmd.java:33) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:66) [support-diagnostics-6.1.jar:6.1]
Execution Error
java.lang.RuntimeException: Diagnostic runtime error
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:44) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:66) ~[support-diagnostics-6.1.jar:6.1]
Caused by: java.lang.NullPointerException: null
	at com.elastic.support.diagnostics.commands.LogAndConfigCmd.execute(LogAndConfigCmd.java:33) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-6.1.jar:6.1]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-6.1.jar:6.1]
	... 1 common frames omitted
root@smp-prod-master-dus10-1:/tmp/support-diagnostics-6.1# ll

```

Stacktrace:

```
java.lang.NullPointerException: null
    at com.elastic.support.diagnostics.commands.LogAndConfigCmd.execute(LogAndConfigCmd.java:33) ~[support-diagnostics-6.1.jar:6.1]
    at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) ~[support-diagnostics-6.1.jar:6.1]
    at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-6.1.jar:6.1]
    at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) ~[support-diagnostics-6.1.jar:6.1]
    at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:66) [support-diagnostics-6.1.jar:6.1]
Execution Error
```

The error appears to happen here: https://github.com/elastic/elasticsearch-support-diagnostics/blob/6.1/src/main/java/com/elastic/support/diagnostics/commands/LogAndConfigCmd.java#L33

**Comment by ppf2** [comment]
+1  Have multiple reports of this from the field. @nemonster

**Comment by nemonster** [comment]
There are actually a few different issues here. Finishing up some testing now, and will push a new version tonight with a email to the group as an alert.
