### ISSUE TITLE
NPE when --scrub option is used with support-diagnostics-6.2

### ISSUE THREAD

**Issue by hoigau** [elastic/elasticsearch-support-diagnostics#183]
Using the support-diagnostics-6.2 with --scrub option throws NullPointerException:

./diagnostics.sh --ssl -u elastic -p  --scrub --host node1.local
```
...
Password redaction: elasticsearch config.
Error redacting config passwords.
java.lang.NullPointerException: null
	at com.elastic.support.diagnostics.commands.ScrubPasswordsCmd.execute(ScrubPasswordsCmd.java:39) ~[support-diagnostics-6.2.jar:6.2]
	at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-6.2.jar:6.2]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) [support-diagnostics-6.2.jar:6.2]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:41) [support-diagnostics-6.2.jar:6.2]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:66) [support-diagnostics-6.2.jar:6.2]
Password removal failed - please examine archive to ensure sensitive information is removed.
Finished processing logs and configuration files.
Scrubbing elasticsearch logs and configuration using scrub.yml.
Scrubbing was enabled but no substitutions were defined. Bypassing log and configuration file processing.
Writing diagnostic manifest.
Archiving diagnostic results.
Archive: /home/unmui/support-diagnostics-6.2/diagnostics-20171109-083154.tar.gz was created
Deleting temporary directories.
```

**Comment by nemonster** [comment]
It appears this was run without sudo. if it's a package install the diagnostic will not be able to read the /etc folder and thus the config files. So it will fail. Please try again using sudo.

**Comment by hoigau** [comment]
@nemonster you're perfectly right, it runs fine with sudo!! sorry for the noise!
