### ISSUE TITLE
Provide Xmx configuration as an option from command line

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch-support-diagnostics#88]
A large cluster state can cause the tool to go oom.

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

at java.util.Arrays.copyOf(Unknown Source)

at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)

at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)

at java.lang.AbstractStringBuilder.append(Unknown Source)

at java.lang.StringBuilder.append(Unknown Source)

at org.springframework.util.StreamUtils.copyToString(StreamUtils.java:74)

at org.springframework.http.converter.StringHttpMessageConverter.readInternal(StringHttpMessageConverter.java:88)

at org.springframework.http.converter.StringHttpMessageConverter.readInternal(StringHttpMessageConverter.java:40)

at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:159)

at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:106)

at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:809)

at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:793)

at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:572)

at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)

at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:448)

at com.elastic.support.diagnostics.RestModule.submitRequest(RestModule.java:27)

at com.elastic.support.diagnostics.commands.RunClusterQueriesCmd.execute(RunClusterQueriesCmd.java:39)

at com.elastic.support.diagnostics.DiagnosticChain.execute(DiagnosticChain.java:31)

at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47)
```

**Comment by dadoonet** [comment]
This stacktrace is not coming from elasticsearch.
Did you report in the wrong place?

BTW we do support setting memory options.

**Comment by dadoonet** [comment]
Oops. Sorry.

**Comment by nemonster** [comment]
With the revised call mechanism this should be less of an issue.  You can bump up the -Xmx with the DIAG_JAVA_OPTS environment variable similar to how you would do in ES so I'm closing this one.
