### ISSUE TITLE
Problem running diagnostic tool 

### ISSUE THREAD

**Issue by ckcartera** [elastic/elasticsearch-support-diagnostics#93]
I get the following error when I run the tool. I can't see where to configure the hostname. Please advise:

Using /usr/java/latest/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Results will be written to: /data/tmp/support-diagnostics-2.0.5
Creating /data/tmp/support-diagnostics-2.0.5/diagnostics as temporary directory.

Configuring REST endpoint.
Trying REST Endpoint.
Error submitting request
:
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://:9200":URI does not specify a valid host name: http://:9200; nested exception is org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http://:9200
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:448) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at com.elastic.support.diagnostics.RestModule.submitRequest(RestModule.java:28) ~[support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:25) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.chain.Chain.execute(Chain.java:33) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:19) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) [support-diagnostics-2.0.5.jar:2.0.5]
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http://:9200
        at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:94) ~[httpclient-4.3.5.jar:4.3.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.5.jar:4.3.5]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        ... 8 common frames omitted
Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified
java.lang.RuntimeException: Please check log file for additional details.
        at com.elastic.support.diagnostics.RestModule.submitRequest(RestModule.java:42) ~[support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:25) ~[support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.chain.Chain.execute(Chain.java:33) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:19) [support-diagnostics-2.0.5.jar:2.0.5]
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) [support-diagnostics-2.0.5.jar:2.0.5]
Exception in thread "main" java.lang.Exception: Error initializing diagnostic chain
        at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:21)
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47)

**Comment by nemonster** [comment]
Perhaps?
--host 192.168.137.1 --port 9201

**Comment by ckcartera** [comment]
Thank you. I already figured out how to do it. I posted the results in a separate ticket
Cheers,
Can

Sent from my iPhone

On Mar 12, 2016, at 1:13 PM, Greg Nieman <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps?
--host 192.168.137.1 --port 9201
