### ISSUE TITLE
_cat/aliases API call fails with Shield, if aliases not in use

### ISSUE THREAD

**Issue by damianpfister** [elastic/elasticsearch-support-diagnostics#94]
Since Shield sees aliases the same as indexes, when aliases are not available it gives a 404 error. Example from a simple curl command as follows:

```
curl http://localhost:9200/_cat/aliases

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index":"_all"}],"type":"index_not_found_exception","reason":"no such index","index":"_all"},"status":404}
```

Error message presented via the diagnostic tool as follows:

```
Currently running the following query:cat_aliases 
Error submitting request 
: 
org.springframework.web.client.HttpClientErrorException: 404 Not Found 
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE] 
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE] 
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE] 
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE] 
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:448) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE] 
at com.elastic.support.diagnostics.RestModule.submitRequest(RestModule.java:28) ~[support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.commands.RunClusterQueriesCmd.execute(RunClusterQueriesCmd.java:41) [support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-2.0.5.jar:2.0.5]
at com.elastic.support.chain.Chain.execute(Chain.java:33) [support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:19) [support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) [support-diagnostics-2.0.5.jar:2.0.5] 
Error retrieving the following diagnostic: cat_aliases - this stat will not be included. 
java.lang.RuntimeException: Please check log file for additional details. 
at com.elastic.support.diagnostics.RestModule.submitRequest(RestModule.java:42) ~[support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.commands.RunClusterQueriesCmd.execute(RunClusterQueriesCmd.java:41) ~[support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd.execute(AbstractDiagnosticCmd.java:15) [support-diagnostics-2.0.5.jar:2.0.5]
at com.elastic.support.chain.Chain.execute(Chain.java:33) [support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:19) [support-diagnostics-2.0.5.jar:2.0.5] 
at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:47) [support-diagnostics-2.0.5.jar:2.0.5]
```

This error does not stop the diagnostic tool from completing, with the only thing missing being the aliases text file, so more of an aesthetics bug.

Is there any way of working around this in the diagnostic tool, by checking for the presence of Shield and if no aliases are found in the cluster state then skip the cat aliases API call?

**Comment by pickypg** [comment]
FYI this is the direct result of this documented limitation (to pass onto the user): https://www.elastic.co/guide/en/shield/current/limitations.html#_changes_in_index_wildcard_behavior

We do have a recent internal issue to change the behavior (feel free to sign them up for the feature request): https://github.com/elastic/x-plugins/issues/1250

**Comment by nemonster** [comment]
OK, but my question here is whether this is an issue with Shield being installed vs. the account the user is running the diagnostic with?  If it's the latter, then my question would be whether this is the equivalent of having to sudo?  It also does beg the question of why _cat/aliases *doesn't work?  Given that getting the cluster state works, and that the aliases are in there, it does raise the question of what they are protecting?

**Comment by nemonster** [comment]
With the revised REST call mechanism that streams the response directly to disk you won't see the full stack trace from now on.  The file will contain the same line as you get from curl, and the there will be a one line warning message with the HTTP code and the reason logged.
